### ISSUE TITLE
need to mix bp.gen.init

### ISSUE THREAD

**Issue by mrchypark** [ufirstgroup/bonny_plug#15]
with MutatingWebhookConfiguration and phoenix server? or plug server.

how about this?

**Comment by mruoss** [comment]
Honestly, I am a bit lost. What is your proposal? A mix task for generating boilerplate code for phx server and webhook config?

**Comment by mruoss** [comment]
Hey @mrchypark 

Yeah I think this would be an overkill. There are the [Phoenix mix tasks](https://hexdocs.pm/phoenix/mix_tasks.html) for spinning up a phoenix application (e.g. `mix phx.new`). From that point it's just following the instructions in the README.md. 

I'm gonna close this. But feel free to reach out for support. Otherwise, for discussions around features, I also activated the [discussion feature](https://github.com/ufirstgroup/bonny_plug/discussions).

**Comment by mrchypark** [comment]
Great. Thank you for package again. :)
